#!/bin/sh
#
# delve - run Golang debugger on reposurgeon
#
# Note: Due to crappy dlv documentation this
# doesn't work yet.
#
# Based on this recipe:
# https://github.com/go-delve/delve/issues/1982
#
cd ..

dlv debug ./surgeon --headless --listen 127.0.0.1:3100 &
serverpid=$!
trap 'kill ${serverpid}' EXIT HUP INT QUIT TERM

sleep 1
dlv connect 127.0.1:3100 
