#!/bin/sh
#
# liftcheck - compare reposurgeon lift of a Subversion repo with a checkout
#
# The -v option reveals executed subcommands.
# The -p option shows revision numbers when comparing multiple revisions
# The -u option enables context-diffing in the compare operation
# The -i option disables the normal suppression of ignore comparisons
# The -d option disables removal of the generated repositories after the run
# The -a option enables progress messages from the Subversion loader.
# The -s option enables display of common files
# The -r option sets a revision to check rather than trunk, branches and tags of HEAD.
#               The corresponding git commit is found with the legacy map, which means
#               only the branch modified in the revision will be compared, unless the
#               -B option is also used to make a flat repository.
#               You can use an integer range min-max, or "all", to check multiple
#               revisions in a row. Non-existing revisions are silently ignored.
# The -R option sets a read limit to the dump parsing, for speed
# The -e option sets exckude patterbs to ignore uninteresting tags and branches
# The -B option makes liftcheck use --nobranch to compare against a flat repository.
#               If the repository has no trunk, this option is enforced.
#
# The REPOSURGEON environment variable can be used to substitute in a
# different implementation.
#
# The TESTOPT variable can be used to pass an early command or option setting
# to reposurgeon.
set -e

export LANG=C

repotoolopt=""
debug=no
compareopt=""
svnquiet=-q
slimit=""
rlimit=""
nobranch=""
progress=no
while getopts ade:ir:R:suvBp opt
do
    case $opt in
	d) debug=yes;;
	p) progress=yes;;
	e) compareopt="${compareopt} -e ${OPTARG}";;
	a) svnquiet="";;
	i|s|u) compareopt="${compareopt} -${opt}";;
	R) slimit="-r ${OPTARG}" rlimit="readlimit ${OPTARG}";;
	r) revision="${OPTARG}";;
	v) repotoolopt="${repotoolopt} -${opt}";;
	u) compareopt="${compareopt} -${opt}";;
	B) nobranch="--nobranch";;
    esac
done
shift $(($OPTIND - 1))

if [ -z "$1" ]
then
    echo "liftcheck: an argument file (a Subversion dump) is required."
    exit 1
fi

what=$1
if [ -f ${what}.svn ]
then
    what=${what}.svn
elif [ ! -f ${what} ]
then
    echo "No script matching ${what} found"
    exit 1
fi

stem=liftcheck$$

rm -fr liftcheck[0123456789]*

if [ $debug = no ]
then
    trap "rm -fr ${stem} ${stem}-checkout ${stem}-git ${stem}.legacy ${stem}.gitmap ${stem}.gfi ${stem}*~" 0 1 2 15
fi

# Make a Subversion repo from the dump
./svn-to-svn ${svnquiet} ${slimit} -c <${what} ${stem}

# Make a git repo from the dump using reposurgeon
${REPOSURGEON:-../reposurgeon} "${TESTOPT}" "${rlimit}" "read ${nobranch} <${what}" \
    "prefer git" "rebuild ${stem}-git" "write >${stem}.gfi" \
    "legacy write>${stem}.legacy" >&-

if [ ! -e ${stem}-checkout/trunk ]
then
    nobranch=--nobranch
fi

if [ -n "${revision}" ]
then
    # Create a list of commits with corresponding legacy map entries
    cd ${stem}-git
    git log --reverse --format="%cd!%an	%H" --date=iso-strict --all | sed 's/+00:00/Z/' > ../${stem}.gitmap
    git for-each-ref --format='%(creatordate:iso-strict)!%(taggername)%(authorname)	%(objectname)' \
        | sed 's/+00:00/Z/' >> ../${stem}.gitmap
    cd ..

    # Filter the git-fast-import stream to keep only the refs of the commits
    grep -B 1 '^#legacy-id' ${stem}.gfi > ${stem}.gfi2
    rm ${stem}.gfi
    mv ${stem}.gfi2 ${stem}.gfi

    if [ ${revision} = "all" ]
    then
        min=1
        max=`cat ${stem}.gitmap | wc -l`
    else
        min=`echo ${revision} | sed 's/-.*$//'`
        max=`echo ${revision} | sed 's/^.*-//'`
    fi

    for revision in `seq ${min} ${max}`
    do
        # Find out the git revision to pass
        id=`grep "^SVN:${revision}[[:space:]]" ${stem}.legacy --max-count=1 | cut -f 2`
        count=`echo ${id} | sed 's/^.*![^:]*\($\|.*:\)//'`
        id=`echo ${id} | sed 's/\(!.*\):[^:]*/\1/'`

        if [ -z "${id}" ]
        then
            continue
        fi
        if [ -z "${count}" ]
        then
            count=1
        fi
        sha=`grep "^${id}" ${stem}.gitmap --max-count=${count} | tail -n 1 | cut -f 2`
        if [ -z "${sha}" ]
        then
            continue
        fi

        # Find the corresponding ref to checkout in SVN
        ref=`grep "^#legacy-id ${revision}$" -B 1 --max-count=1 ${stem}.gfi | sed -n 's!^commit refs/!!; t print; q; :print; p; q'`
        if [ -z "${ref}" ]
        then
            continue
        fi

        refopt=`echo ${ref} | sed 's!^deleted/r[^/]*/!!; s!^tags/!-t !; s!^heads/!-b !'`

        if [ ${progress} != no ]
        then
            echo "Checking lift at r${revision} (${refopt})"
        fi
        # Compare the original with the lift
        ../repotool ${repotoolopt} compare ${compareopt} \
            ${nobranch} ${refopt} -r ${revision}:${sha} \
            ${stem}-checkout ${stem}-git
    done
else

    # Compare the original with the lift
    ../repotool ${repotoolopt} compare-all ${compareopt} ${nobranch} \
                                           ${stem}-checkout ${stem}-git

fi

if [ $debug != no ]
then
    ls -d liftcheck[0123456789]*
fi

# end
