#!/bin/sh
#
# sd-to-fi - Subversion dump on stdin to fast-import on stout
#
# Relies on repostreamer bein where BIN declares it.
#
# With the -n option, create a repo corresponding to the input file
# and check out a working copy for editing, but do not stream the
# result to stdout and do not delete the repo.
#
# With the -r option, expect the repo to exist, pick it
# up with repostreamer, and throw the result to stdout; then
# do not delete the repo.
#
# With the -d option, expect the repo to exist, undump the repo to
# an sd file; then do not delete the repo.
#
# The -v option argument will be used to set reposurgeon's verbose option.
#
# The -t option allows property extensions to be generated.  It's turned
# off by default because git-import chokes on it.
#
# To add complexity to a test load, do -n, then edit the test repo with
# Subversion, then use -d. Note: you must commit to force the repo to
# be up to date before streaming it. 
#
BIN=../..

extract=T
view=F
stream=T
undump=F
cleanup=T
verbose="0"
# Suppress fossil emission by default
streamopts='prefer git'

while getopts dgnrtv: opt
do
    case $opt in
	n) extract=T ; view=F ; stream=F ; undump=F ; cleanup=F ;;
        g) extract=F ; view=T ; stream=F ; undump=F ; cleanup=F ;;
        r) extract=F ; view=F ; stream=T ; undump=F ; cleanup=F ;;
        d) extract=F ; view=F ; stream=F ; undump=T  ; cleanup=F ;;
	t) streamopts="" ;;
	v) verbose="$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))

# Should we build a repo from the input file?
if [ $extract = T ]
then
    rm -fr test-repo test-checkout
    svnadmin create test-repo
    svnadmin load test-repo >/dev/null
    svn co file://${PWD}/test-repo test-checkout >/dev/null
fi

# Should we view the repo?
if [ $view = T ]
then
    (cd test-repo >/dev/null; {BIN}/reposurgeon "verbose $verbose" "read ." "prefer git" "rebuild /tmp/testrepo"; cd /tmp/testrepo; gitk --all --tags)
fi

# Should we stream the repo?
if [ $stream = T ]
then
    (cd test-checkout >/dev/null; ${BIN}/reposurgeon "verbose $verbose" "read ." "$streamopts" "write")
fi

# Should we undump the repo?
if [ $undump = T ]
then
    svnadmin dump test-repo
fi

# Should we clean up the test directory
if [ $cleanup = T ]
then
    rm -fr test-repo test-checkout
fi
