#!/bin/sh
#
# setpython - create a local link from 'python' to a specified version
#
# This script is used to to redirect the 'python' in reposurgeon's
# shebang line to a specified version when running regression tests.

if [ -z "$1" ]
then
	if [ -e python ]
	then
		readlink python
	else
		command -v python
	fi
elif [ $1 = "python" ]
then
	rm -f ./python
	echo "python -> `command -v python`"
elif [ $1 = python2 -o $1 = python3 ]
then
	p=`command -v $1`
	case $p in
		*/bin/*) ln -sf $p ./python; echo "python -> $p";;
		*) echo "setpython: no python binary" >&2; exit 1;;
	esac
else
	echo "setpython: unrecognized python version" >&2
	exit 1
fi

exit 0
