#!/bin/sh
# singletest - run a single regression test
#
# The REPOSURGEON environment variable can be used to substitute in a
# different implementation.

. ./common-setup.sh

# Use absolute path so tests that change working directory still use 
# scripts from parent directory.  Note that using $PWD seems to fail
# here under Gitlab's CI environment.
PATH=$(realpath ..):$(realpath .):${PATH}

# Without this, under CentOS Python may emit invisible ANSI strings
# that confuse diff.  Leave this in while pyreposurgeon still exists.
TERM=dumb

what=`echo ${1} | sed -e '/-FAILED/s///' -e '/.tst/s///'`

if [ -f ${what}.tst ]
then
    tst=${what}.tst
    chk=${what}.chk
elif [ -f ${what}.tst-FAIL ]
then
    tst=${what},tst-FAIL
    chk=${what}.chk
    echo "Expect a diff"
else
    echo "No script matching ${what} found"
    exit 1
fi

for x in $*;
do
    echo "Test $x"
    ${REPOSURGEON:-reposurgeon} "script ${tst}" 2>&1 | diff -u ${chk} -
done
