#!/bin/sh
# singlelift - run a single Subversion conversion test
#
# With -d, dump the conversion to stdout rather than diffing against
# the check file.
#
# With -v, set the verbosity level. (Probaly only useful in dump mode.)
#
# With -x, set the experimental bit.
#
# The REPOSURGEON environment variable can be used to substitute in a
# different implementation.

. common-setup.sh

# Use absolute path so tests that change working directory still use 
# scripts from parent directory.  Note that using $PWD seems to fail
# here under Gitlab's CI environment.
PATH=$(realpath ..):$(realpath .):${PATH}

# Without this, under CentOS Python may emit invisible ANSI strings
# that confuse diff. Leave this in whle pyreposurgeon still exists.
TERM=dumb

mode=check
verbose=0
experimental=""
while getopts dv:x opt
do
    case $opt in
	d) mode=dump;;
	v) verbose="$OPTARG" ;;
	x) experimental="set experimental"
    esac
done
shift $(($OPTIND - 1))

for x in $*;
do
    grep '^ #' ${x}.svn 2>/dev/null
    case $mode in
	dump)
	    ${REPOSURGEON:-reposurgeon} "verbose $verbose" "$experimental" "read <${x}.svn" "prefer git" "write -" 2>&1;;
	*)
	    ${REPOSURGEON:-reposurgeon} "verbose $verbose" "$experimental" "read <${x}.svn" "prefer git" "write -" 2>&1 | diff -u ${x}.chk - ;;
    esac
done
