#!/bin/sh

. ././common-setup.sh

# Use absolute path so tests that change working directory still use 
# scripts from parent directory.  Note that using $PWD seems to fail
# here under Gitlab's CI environment.
PATH=$(realpath ..):$(realpath .):${PATH}

# Without this, under CentOS Python may emit invisible ANSI strings
# that confuse diff.  Leave this in while pyreposurgeon still exists.
TERM=dumb

experimental=""
serial=""
diff=yes
build=no
log=""
while getopts bhl:osx opt
do
    case $opt in
	b) build=yes;; 
	l) log="log $OPTARG" ;;
	o) diff=no ;;
	s) serial="set serial";;
	x) experimental="set experimental";;
	*) cat <<EOF
singletest - run a single regression test

The REPOSURGEON environment variable can be used to substitute in a
different implementation.

With -b. regenerate the corresponding check file

With -h, display this option summary.

With -l, set log bits (only with -o)

With -o, domp the test output rather than diffing against the checkfile

With -s, set the serial flag to disable parallelism

With -x, set the experimental flag.
EOF
	   exit 0;;
    esac
done
shift $(($OPTIND - 1))

what=`echo ${1} | sed -e '/-FAILED/s///' -e '/.tst/s///'`

if [ -f ${what}.tst ]
then
    tst=${what}.tst
    chk=${what}.chk
elif [ -f ${what}.tst-FAIL ]
then
    tst=${what}.tst-FAIL
    chk=${what}.chk
    echo "Expect a diff"
elif [ -z ${what} ]
then
    exec $0 -h
else
    echo "No script matching ${what} found"
    exit 1
fi

for x in $*;
do
    # This redirect to stderr is so this script can be used to rebuild checkfiles
    (grep '^##' ${tst} 2>/dev/null) 1>&2
    if [ $diff = yes ]
    then
        ${REPOSURGEON:-reposurgeon} "$serial" "$experimental" "script ${tst}" 2>&1 | diff -u ${chk} -
    elif [ $build = yes ] 
    then
        ${REPOSURGEON:-reposurgeon} "$serial" "$experimental" "script ${tst}" >${tst}.chk 2>&1
    else
        ${REPOSURGEON:-reposurgeon} "$log" "$serial" "$experimental" "script ${tst}" 2>&1
    fi
done

# Return exit status of the last command to run.
# In particular, if the last command was a diff,
# this will return 0 for empty and 1 for nonempty.
# Otherwise you'll typically get the exit status
# of reposurgeon. 
exit $?
