#!/bin/sh
# singlelift - run a single Subversion conversion test
#
# With -l, set reposurgeon log flags (dump mode only).
#
# With -s, force serial execution - disables parallelism.
#
# With -o, dump the conversion to stdout rather than diffing against
# the check file.
#
# With -x, set the experimental flag.
#
# The REPOSURGEON environment variable can be used to substitute in a
# different implementation.

. ./common-setup.sh

# Use absolute path so tests that change working directory still use 
# scripts from parent directory.  Note that using $PWD seems to fail
# here under Gitlab's CI environment.
PATH=$(realpath ..):$(realpath .):${PATH}

# Without this, under CentOS Python may emit invisible ANSI strings
# that confuse diff. Leave this in whle pyreposurgeon still exists.
TERM=dumb

mode=check
log=""
experimental=""
while getopts l:osx opt
do
    case $opt in
	l) log="log $OPTARG" ;;
	o) mode=dump;;
	s) serial="set serial";;
	x) experimental="set experimental"
    esac
done
shift $(($OPTIND - 1))

for x in $*;
do
    case $x in
	*.svn) x=`echo "$x" | sed '/.svn/s///'`;;
    esac
    grep '^ #' ${x}.svn 2>/dev/null
    case $mode in
	dump)
	    ${REPOSURGEON:-reposurgeon} "$log" "$serial" "$experimental" "read <${x}.svn" "prefer git" "write -" 2>&1;;
	*)
	    ${REPOSURGEON:-reposurgeon} "$serial" "$experimental" "read <${x}.svn" "prefer git" "write -" 2>&1 | diff -u ${x}.chk - ;;
    esac
done
