#!/bin/sh
# singletest - run a single regression test
#
# The REPOSURGEON environment variable can be used to substitute in a
# different implementation.
#
# With -v, set the verbosity level.  (Not likely to give useful results.)
#
# With -x, set the experimental bit.

. ./common-setup.sh

# Use absolute path so tests that change working directory still use 
# scripts from parent directory.  Note that using $PWD seems to fail
# here under Gitlab's CI environment.
PATH=$(realpath ..):$(realpath .):${PATH}

# Without this, under CentOS Python may emit invisible ANSI strings
# that confuse diff.  Leave this in while pyreposurgeon still exists.
TERM=dumb

verbose=0
experimental=""
serial=""
while getopts sv:x opt
do
    case $opt in
	s) serial="set serial";;
	v) verbose="$OPTARG" ;;
	x) experimental="set experimental"
    esac
done
shift $(($OPTIND - 1))

what=`echo ${1} | sed -e '/-FAILED/s///' -e '/.tst/s///'`

if [ -f ${what}.tst ]
then
    tst=${what}.tst
    chk=${what}.chk
elif [ -f ${what}.tst-FAIL ]
then
    tst=${what},tst-FAIL
    chk=${what}.chk
    echo "Expect a diff"
else
    echo "No script matching ${what} found"
    exit 1
fi

for x in $*;
do
    grep '^##' ${tst} 2>/dev/null
    ${REPOSURGEON:-reposurgeon} "$serial" "$experimental" "script ${tst}" 2>&1 | diff -u ${chk} -
done
