#!/bin/sh
#
# svn-to-svn - Subversion dump on stdin to dump on stdout
#
# With the -n option, create a repo corresponding to the input file
# and check out a working copy for editing, but do not stream the
# result to stdout and do not delete the repo.
#
# With the -d option, expect the repo to exist, undump the repo to
# a Subversion dump file; then do not delete the repo.
#
# With the -r option, expect the repo to exist, pick it up with
# reposurgeon, and throw the result to stdout as an import stream;
# then do not delete the repo.
#
# The -v option argument will be used to set reposurgeon's verbose option.
#
# The -s op[tion strips out generated time-varying headers - the UUID and
# the timestamp in revision zero.  This is necessary for file comparisons 
# in regression tests.
#
# The -t option allows property extensions to be generated.  It's turned
# off by default because git-import chokes on it.
#
# With the -e option, edit a Subversion dumpfile and rebuild it, fixing
# the checksum headers.
#
# To add complexity to a test load, do -n, then edit the test repo with
# Subversion, then use -d. Note: you must commit to force the repo to
# be up to date before streaming it. 
#
PATH=$PATH:../..

extract=T
view=F
edit=F
stream=F
undump=T
cleanup=T
strip=F
verbose="0"
# Suppress fossil emission by default
streamopts='prefer git'

while getopts degnrstv: opt
do
    case $opt in
        e) extract=F; view=F; edit=T; stream=F; undump=F; cleanup=T strip=F;;
	n) extract=T; view=F; edit=F; stream=F; undump=F; cleanup=F strip=F;;
        g) extract=F; view=T; edit=F; stream=F; undump=F; cleanup=F strip=F;;
        r) extract=F; view=F; edit=F; stream=T; undump=F; cleanup=F strip=F;;
        d) extract=F; view=F; edit=F; stream=F; undump=T; cleanup=F strip=F;;
        s) extract=F; view=F; edit=F; stream=F; undump=F; cleanup=F strip=T;;
	t) streamopts="" ;;
	v) verbose="$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))

# Should we strip time-varying headers out of the input dump file?
if [ $strip = T ]
then
    sed \
	-e '/^UUID.*/s//UUID LINE MUNGED FOR REGRESSION-TEST PURPOSES/' \
	-e '/^[0-9]/s/.*/DATE LINE MUNGED FOR REGRESSION-TEST PURPOSES/'
fi

# Should we build a repo from the input file?
if [ $extract = T ]
then
    rm -fr test-repo test-checkout
    svnadmin create test-repo
    svnadmin load test-repo >/dev/null
    svn co file://${PWD}/test-repo test-checkout >/dev/null
fi

# Should we edit the streamfile?
if [ $edit = T ]
then
    dump=$1
    if [ -z $dump ]
    then
	echo "svn-to-svn: a file argument is required" >&2
	exit 1
    elif $EDITOR $1
    then
	rm -fr test-repo test-checkout
	svnadmin create test-repo
	sed  <$dump \
	    -e '/Text-content-md5: /d' -e '/Text-content-sha1: /d' \
	    -e '/Text-copy-source-md5: /d' -e '/Text-copy-source-sha1: /d' \
	    | svnadmin load test-repo >/dev/null
	svnadmin dump test-repo >$dump
    fi
fi

# Should we view the repo?
if [ $view = T ]
then
    (cd test-repo >/dev/null; {BIN}/reposurgeon "verbose $verbose" "read ." "prefer git" "rebuild /tmp/testrepo"; cd /tmp/testrepo; gitk --all --tags)
fi

# Should we stream the repo?
if [ $stream = T ]
then
    reposurgeon "verbose $verbose" "read test-repo" "$streamopts" "write"
fi

# Should we undump the repo?
if [ $undump = T ]
then
    svnadmin dump test-repo
fi

# Should we clean up the test directory
if [ $cleanup = T ]
then
    rm -fr test-repo test-checkout
fi
