= Installation instructions =

== Quick recipe for systems using apt ==

---------------------------------------------------------------------------
sudo apt-get install golang hg-git-fast-import      # For running
sudo apt-get install asciidoctor                    # To render docs
sudo apt-get install golint shellcheck              # For testing
sudo apt-get install subversion mercurial rsync cvs # For testing
sudo apt-get install cvs-fast-export                # For testing
sudo apt-get install gnuplot                        # For benchmarking
make                                                # Build it
make check                                          # Run the tests
---------------------------------------------------------------------------

== Prerequisites ==

You will need 64-bit hardware. This code is not intended to run on
32-bit machines (which have an address space too small to be useful
for surgwey on large repositories) and may not even build on them.

You will need git at version 2.19.2 or later.  Versions of reposurgeon
after 4.7 assume the --show-original-ids option of git-fast-export is
available.

You will need the Go compiler at revision 1.12 or later.  Note, you
may have to tweak your $PATH variable to make the Go tools visible.

hg-git-fast-import is required if yiou want to write Mercurial
repositories, but not to read them.

A few scripts are written in shell. Any Bourne-shell-like
implementation will do. The restricted shell shipped on Debian/Ubuntu
will work. Shell is almost certainly already installed on your system.

You will need asciidoctor to format the documentation.

golint, shellcheck, subversion, mercurial, cvs, cvs-fast-export and
rsync are required for the full regression tests, but not for running
the code.  Very old versions of Subversion (certainly 1.6 or earlier,
but not 1.9 or later) will cause one spurious test failure.

gnuplot is only required if you're planning to try performance-tuning
with repobench.

== Building the software ==

To build the tools, simply run "make" in the toplevel directory.  This
also builds the suite documentation.

== Testing the software ==

There is an extensive regression-test suite in the `test/` directory.
To test the correctness of this software once its prerequisites are
installed, invoke `make check` in the main directory.

== Note to packagers ==

It probably is not necessary to package repobench, as it is
a benchmarking tool only of interest to developers working
with the source distribution.

// end
